name: 'pxSocial'
version: '0.1'
main: 'io.github.winnpixie.pixiecraft.social.plugin.PxSocialPlugin'
api-version: 26.2
depend:
  - 'pxCommons'

commands:
  channel:
    description: 'Set or clear your chat messaging channel.'
    usage: '/channel [channel]'
  chat-filter:
    aliases: [ 'chatfilter', 'filter' ]
    description: 'Toggle chat message filters.'
    usage: '/chat-filter <uwu|leet>'
  chat-color:
    aliases: [ 'chatcolor', 'color', 'cc' ]
    description: 'Set your chat message color.'
    usage: '/chat-color [RRGGBB]'
  nickname:
    aliases: [ 'nick' ]
    description: 'Set your chat nickname.'
    usage: '/nickname [name]'
  whisper:
    aliases: [ 'message', 'msg', 'pm', 'tell', 'w' ]
    description: 'Privately send <message> to <receiver>.'
    usage: '/whisper <receiver> <message>'