name: 'pxCore'
version: '0.1'
main: 'io.github.winnpixie.pixiecraft.core.plugin.PxCorePlugin'
api-version: 26.2
depend:
  - 'pxCommons'

commands:
  hat:
    description: 'Equip any item in your main hand as a helmet'
    usage: '/hat'
  ping:
    description: 'View the latency of yourself or [player]'
    usage: '/ping [player]'
  seen:
    description: 'View when [target] last joined'
    usage: '/seen <player>'
  store-experience:
    description: 'Store [levels] of experience within a book, or all if none is specified'
    usage: '/store-experience [levels]'