name: 'pxEconomy'
version: '0.1'
main: 'io.github.winnpixie.pixiecraft.economy.plugin.PxEconomyPlugin'
api-version: 1.21
depend:
  - 'pxCommons'

commands:
  economy:
    aliases: [ 'eco' ]
    description: 'Manage the economy.'
  balance:
    aliases: [ 'bal' ]
    description: 'View the wallet balance of yourself or another online.'
    usage: '/balance [user]'
  bank:
    description: "Manage your bank accounts."
    usage: "/bank <open|close|accounts|balance|deposit|withdraw> [account] [balance]"